apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: saunah-cert
  namespace: default
spec:
  commonName: booking.saunah.ch
  secretName: saunah-cert
  dnsNames:
    - booking.saunah.ch
    - api.booking.saunah.ch
  issuerRef:
    name: letsencrypt-prod #letsencrypt-staging
    kind: ClusterIssuer
