# Default values for saunah-database.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

postgresql:
  namespace: class-pm4-2022-7-prod
  auth:
    enablePostgresUser: false
    username: saunah
    existingSecret: saunah-secrets-database
    database: saunah
  architecture: replication
  primary:
    service:
      type: ClusterIP
      ports:
        postgresql: 5432
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 100m
        memory: 256Mi
  readReplicas:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 100m
        memory: 256Mi
  metrics:
    enabled: false
  volumePersmissions:
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
