apiVersion: v1
kind: Service
metadata:
  name: {{ include "saunah-backend.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "saunah-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http8080
      protocol: TCP
      name: http8080
  selector:
    {{- include "saunah-backend.selectorLabels" . | nindent 4 }}
