apiVersion: v1
kind: Secret
metadata:
  name: saunah-secrets-object-storage
  namespace: {{ .Values.namespace }}
data:
  accessKey: {{ .Values.secrets.objectStorage.accessKey }}
  secretKey: {{ .Values.secrets.objectStorage.secretKey }}
type: Opaque
