apiVersion: v1
kind: Secret
metadata:
  name: saunah-secrets-credentials
  namespace: {{ .Values.namespace }}
data:
  googleServiceAccount: {{ .Values.secrets.credentials.googleServiceAccount }}
  googleCalendarApiKey: {{ .Values.secrets.credentials.googleCalendarApiKey }}
type: Opaque
