apiVersion: v1
kind: Secret
metadata:
  name: saunah-secrets-database
  namespace: {{ .Values.namespace }}
data:
  password: {{ .Values.secrets.database.password }}
  replication-password: {{ .Values.secrets.database.password }}
type: Opaque
