apiVersion: v1
kind: Secret
metadata:
  name: saunah-secrets-smtp
  namespace: {{ .Values.namespace }}
data:
  username: {{ .Values.secrets.smtp.username }}
  password: {{ .Values.secrets.smtp.password }}
type: Opaque
