name: Build & Test

on:
  workflow_call:

jobs:
  build:
    name: Build & Run Tests with Gradle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build and Test with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
