name: Build & Test

on:
  workflow_call:

jobs:
  build:
    name: Build & Run Tests with Gradle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build and Test with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
     - name: Cache Gradle packages
         uses: actions/cache@v1
         with:
           path: ~/.gradle/caches
           key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
           restore-keys: ${{ runner.os }}-gradle
         - name: Cache SonarCloud packages
           uses: actions/cache@v1
           with:
             path: ~/.sonar/cache
             key: ${{ runner.os }}-sonar
             restore-keys: ${{ runner.os }}-sonar
         - name: Build and analyze
           run: ./gradlew build jacocoTestReport sonarqube --info
           env:
             # Needed to get some information about the pull request, if any
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
             # SonarCloud access token should be generated from https://sonarcloud.io/account/security/
             SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

