# This workflow tests the SauNah backend application, generates an image,
# deploys it to ghcr.io and then deploys the application to a kubernetes
# cluster.

name: Build, Test & Deploy SauNah backend

on:
  push:

jobs:
  setup:
    name: Setup Configuration Values
    uses: ./.github/workflows/setup.yml

  build:
    name: Build & Run Tests with Gradle
    needs: [setup]
    uses: ./.github/workflows/build.yml

  container:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Create and Publish Container
    needs: [setup, build]
    uses: ./.github/workflows/container.yml
    with:
      containerTag: ${{ needs.setup.outputs.containerTag }}

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Deploy Container to Kubernetes Cluster
    needs: [setup, container]
    uses: ./.github/workflows/deploy.yml
    with:
      containerTag: ${{ needs.setup.outputs.containerTag }}
      k8sNamespace: ${{ needs.setup.outputs.k8sNamespace }}
      k8sContext: ${{ needs.setup.outputs.k8sContext }}
      k8sBackendValues: ${{ needs.setup.outputs.k8sBackendValues }}
