# This workflow tests the SauNah backend application.

name: Test SauNah backend

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    name: Build & Run Tests with Gradle
    uses: ./.github/workflows/build.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
