# This workflow tests the SauNah backend application, generates an image,
# deploys it to ghcr.io and then deploys the application to a kubernetes
# cluster to the staging environment.

name: Build, Test & Deploy to Production

on:
  push:
    tags:
      - v*

env:
  K8S_CONTEXT: init-lab-prod
  HELM_VALUES_NAME: values-prod.yaml

jobs:
  setup:
    name: Setup Configuration Values
    uses: ./.github/workflows/setup.yml

  build:
    name: Build & Run Tests with Gradle
    uses: ./.github/workflows/build.yml

  container:
    name: Create and Publish Container
    needs: [build]
    uses: ./.github/workflows/container.yml
    with:
      containerTag: ${{ needs.setup.outputs.containerTag }}

  deploy:
    name: Deploy Container to Kubernetes Cluster
    needs: [container]
    uses: ./.github/workflows/deploy.yml
    with:
      containerTag: ${{ needs.setup.outputs.containerTag }}
      context: ${{ env.K8S_CONTEXT }}
      valuesName: ${{ env.HELM_VALUES_NAME }}
    secrets:
      k8sConfig: ${{ secrets.K8S_CONFIG }}
