# This workflow tests the SauNah backend application and
# analyses it with Sonar Cloud.

name: Test & Analyse

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    name: Build, Run Tests & Analyse with Gradle
    uses: ./.github/workflows/build.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      CREDENTIALS_GOOGLE_SERVICE: ${{ secrets.CREDENTIALS_GOOGLE_SERVICE }}
