name: Build, Test & Deploy SauNah backend

on:
  workflow_call:
    outputs:
      containerTag:
        value: ${{ jobs.setup.outputs.containerTag }}
      k8sContext:
        value: ${{ jobs.setup.outputs.k8sContext }}
      k8sBackendValues:
        value: ${{ jobs.setup.outputs.k8sBackendValues }}

jobs:
  setup:
    name: Setup Configuration Values
    runs-on: ubuntu-latest
    outputs:
      containerTag: ${{ steps.setConfigs.outputs.containerTag }}
      k8sContext: ${{ steps.setConfigs.outputs.k8sContext }}
      k8sBackendValues: ${{ steps.setConfigs.outputs.k8sBackendValues }}
    steps:
    - uses: actions/checkout@v2
    - name: Set Tag Ouput Variable
      id: setConfigs
      run: |
        echo $(git branch --contains tags/${{ github.ref_name }} | cut -c 3-)
        if [ "${{ github.ref_type }}" == "tag" ] && [ "$(git branch --contains tags/${{ github.ref_name }} | cut -c 3-)" == "feature/improve-actions" ]
        then
          echo "::set-output name=containerTag::${{ github.ref_name }}"
          echo "::set-output name=k8sContext::init-lab-prod"
          echo "::set-output name=k8sBackendValues::values-prod.yaml"
        else
          echo "::set-output name=containerTag::$(echo ${{ github.sha }} | cut -c 1-7)"
          echo "::set-output name=k8sContext::init-lab-staging"
          echo "::set-output name=k8sBackendValues::values-staging.yaml"
        fi
