name: Build, Test & Deploy SauNah backend

on:
  workflow_call:
    outputs:
      containerTag:
        value: ${{ jobs.setup.outputs.containerTag }}

jobs:
  setup:
    name: Setup Configuration Values
    runs-on: ubuntu-latest
    outputs:
      containerTag: ${{ steps.setConfigs.outputs.containerTag }}
    steps:
    - uses: actions/checkout@v2
    - name: Set Tag Ouput Variable
      id: setConfigs
      run: |
        if [ "${{ github.ref_type }}" == "tag" ]
        then
          echo "::set-output name=containerTag::${{ github.ref_name }}"
        else
          echo "::set-output name=containerTag::$(echo ${{ github.sha }} | cut -c 1-7)"
        fi
